export const PLACE_OF_SUPPLY = [
  { id: 1, label: "Jammu & Kashmir", value: "01" },
  { id: 2, label: "Himachal Pradesh", value: "02" },
  { id: 3, label: "Punjab", value: "03" },
  { id: 4, label: "Chandigarh", value: "04" },
  { id: 5, label: "Uttarakhand", value: "05" },
  { id: 6, label: "Haryana", value: "06" },
  { id: 7, label: "Delhi", value: "07" },
  { id: 8, label: "Rajasthan", value: "08" },
  { id: 9, label: "Uttar Pradesh", value: "09" },
  { id: 10, label: "Bihar", value: "10" },
  { id: 11, label: "Sikkim", value: "11" },
  { id: 12, label: "Arunachal Pradesh", value: "12" },
  { id: 13, label: "Nagaland", value: "13" },
  { id: 14, label: "Manipur", value: "14" },
  { id: 15, label: "Mizoram", value: "15" },
  { id: 16, label: "Tripura", value: "16" },
  { id: 17, label: "Meghalaya", value: "17" },
  { id: 18, label: "Assam", value: "18" },
  { id: 19, label: "West Bengal", value: "19" },
  { id: 20, label: "Jharkhand", value: "20" },
  { id: 21, label: "Odisha", value: "21" },
  { id: 22, label: "Chhattisgarh", value: "22" },
  { id: 23, label: "Madhya Pradesh", value: "23" },
  { id: 24, label: "Gujarat", value: "24" },
  { id: 25, label: "Dadra & Nagar Haveli and Daman & Diu", value: "26" },
  { id: 26, label: "Maharashtra", value: "27" },
  { id: 27, label: "Karnataka", value: "29" },
  { id: 28, label: "Goa", value: "30" },
  { id: 29, label: "Lakshadweep", value: "31" },
  { id: 30, label: "Kerala", value: "32" },
  { id: 31, label: "Tamil Nadu", value: "33" },
  { id: 32, label: "Puducherry", value: "34" },
  { id: 33, label: "Andaman & Nicobar Islands", value: "35" },
  { id: 34, label: "Telangana", value: "36" },
  { id: 35, label: "Andhra Pradesh", value: "37" },
  { id: 36, label: "Ladakh", value: "38" },
  { id: 37, label: "Other Territory", value: "97" },
  { id: 38, label: "Centre Jurisdiction", value: "99" },
] as const;

export const PLACE_OF_SUPPLY_VALUES = PLACE_OF_SUPPLY.map(option => option.value);